language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t yevhenkhabarov/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true yevhenkhabarov/docker-react-test yarn test -- --coverage